services:
  - type: web
    name: spring-backend
    env: native
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar

    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk

      - key: MONGO_URI
        value: mongodb+srv://LAKSHMAN:lakshman@cluster0.4unosvn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

      - key: JWT_SECRET
        value: supersecretkeysupersecretkeysupersecretkey!
