services:
  - type: web
    name: spring-backend
    env: native
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar

    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
